name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["main"]

jobs:
  login-and-pull-qa:
    if: github.ref == 'refs/heads/QA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/qa:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/qa:latest

  login-and-pull-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prd:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/prd:latest

  ssh-connect-ec2-QA01:
    needs: [login-and-pull-qa]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_QA01 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_QA }}

  ssh-connect-ec2-QA02:
    needs: [login-and-pull-qa]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_QA02 }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_QA }}

  ssh-connect-ec2-PRD01:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD01 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD02:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD02 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD03:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD03 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}

  ssh-connect-ec2-PRD04:
    needs: [login-and-pull-main]
    uses: ./.github/workflows/setup_docker.yml
    secrets:
      ec2_host: ${{ secrets.EC2_HOST_PRD04 }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_PRD }}